name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-page:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Bundle web resources
        run: |
          npm install
          npx vite build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - run: cp ./vercel.json ./dist
      - uses: amondnet/vercel-action@v25
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./dist

